import Sidebar from "@/components/Sidebar";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Detrator Task",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body style={{ display: "flex", flexDirection: "row-reverse" }}>
        <Sidebar />
        <main
          style={{
            flex: 1,
            height: "100vh",
            overflow: "auto",
            padding: "20px 0",
          }}
        >
          {children}
        </main>
      </body>
    </html>
  );
}
